// Electronics products data - used across the site
export interface Product {
  id: string
  slug: string
  name_en: string
  name_sq: string
  short_description_en: string
  short_description_sq: string
  description_en: string
  description_sq: string
  price_all: number
  price_eur: number
  original_price_all?: number
  original_price_eur?: number
  product_images: { image_url: string; is_primary: boolean }[]
  is_on_sale: boolean
  is_in_stock: boolean
  rating_average: number
  rating_count: number
  category: string
  brand: string
  specs?: { label: string; value: string }[]
}

export const products: Product[] = [
  // COMPUTERS & LAPTOPS
  {
    id: "1",
    slug: "macbook-pro-16-m3",
    name_en: "MacBook Pro 16\" M3 Pro",
    name_sq: "MacBook Pro 16\" M3 Pro",
    short_description_en: "Apple M3 Pro chip, 18GB RAM, 512GB SSD",
    short_description_sq: "Apple M3 Pro çip, 18GB RAM, 512GB SSD",
    description_en: "The most advanced MacBook Pro ever. With the M3 Pro chip, you get groundbreaking performance for demanding workflows like video editing and software development.",
    description_sq: "MacBook Pro më i avancuar ndonjëherë. Me çipin M3 Pro, merrni performancë revolucionare për punë të kërkueshme si editim video dhe zhvillim softuerësh.",
    price_all: 349900,
    price_eur: 2999,
    original_price_all: 399900,
    original_price_eur: 3499,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800", is_primary: true },
      { image_url: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800", is_primary: false },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.8,
    rating_count: 124,
    category: "computers",
    brand: "Apple",
    specs: [
      { label: "Processor", value: "Apple M3 Pro" },
      { label: "RAM", value: "18GB Unified Memory" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: "16.2\" Liquid Retina XDR" },
      { label: "Battery", value: "Up to 22 hours" },
    ],
  },
  {
    id: "2",
    slug: "dell-xps-15-2024",
    name_en: "Dell XPS 15 (2024)",
    name_sq: "Dell XPS 15 (2024)",
    short_description_en: "Intel Core Ultra 7, 32GB RAM, OLED Display",
    short_description_sq: "Intel Core Ultra 7, 32GB RAM, Ekran OLED",
    description_en: "Experience stunning visuals on the 15.6\" 3.5K OLED display. Powered by Intel Core Ultra 7 for exceptional performance.",
    description_sq: "Përjetoni pamje mahnitëse në ekranin 15.6\" 3.5K OLED. Fuqizuar nga Intel Core Ultra 7 për performancë të jashtëzakonshme.",
    price_all: 219900,
    price_eur: 1899,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.5,
    rating_count: 67,
    category: "computers",
    brand: "Dell",
    specs: [
      { label: "Processor", value: "Intel Core Ultra 7 155H" },
      { label: "RAM", value: "32GB DDR5" },
      { label: "Storage", value: "1TB NVMe SSD" },
      { label: "Display", value: "15.6\" 3.5K OLED" },
    ],
  },
  {
    id: "3",
    slug: "asus-rog-strix-g16",
    name_en: "ASUS ROG Strix G16 Gaming Laptop",
    name_sq: "ASUS ROG Strix G16 Laptop Gaming",
    short_description_en: "Intel i9-14900HX, RTX 4070, 240Hz Display",
    short_description_sq: "Intel i9-14900HX, RTX 4070, Ekran 240Hz",
    description_en: "Dominate the competition with cutting-edge Intel Core i9 and NVIDIA RTX 4070 graphics.",
    description_sq: "Dominoni konkurrencën me Intel Core i9 dhe grafikë NVIDIA RTX 4070 të fundit.",
    price_all: 229900,
    price_eur: 1999,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 89,
    category: "computers",
    brand: "ASUS",
  },
  // PHONES & TABLETS
  {
    id: "4",
    slug: "iphone-15-pro-max",
    name_en: "iPhone 15 Pro Max 256GB",
    name_sq: "iPhone 15 Pro Max 256GB",
    short_description_en: "6.7\" Super Retina XDR, A17 Pro chip, Titanium",
    short_description_sq: "6.7\" Super Retina XDR, A17 Pro çip, Titanium",
    description_en: "iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and a 48MP camera system.",
    description_sq: "iPhone 15 Pro Max. I ndërtuar në titanium dhe me çipin revolucionar A17 Pro, buton Action të personalizueshëm, dhe sistem kamere 48MP.",
    price_all: 159900,
    price_eur: 1399,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800", is_primary: true },
      { image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800", is_primary: false },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.9,
    rating_count: 256,
    category: "phones",
    brand: "Apple",
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR" },
      { label: "Chip", value: "A17 Pro" },
      { label: "Camera", value: "48MP Main + 12MP Ultra Wide" },
      { label: "Storage", value: "256GB" },
    ],
  },
  {
    id: "5",
    slug: "samsung-galaxy-s24-ultra",
    name_en: "Samsung Galaxy S24 Ultra",
    name_sq: "Samsung Galaxy S24 Ultra",
    short_description_en: "6.8\" Dynamic AMOLED, 200MP Camera, S Pen",
    short_description_sq: "6.8\" Dynamic AMOLED, 200MP Kamera, S Pen",
    description_en: "Meet Galaxy S24 Ultra, the ultimate form of Galaxy Ultra with Galaxy AI. It's an Icons design with a new titanium frame.",
    description_sq: "Takoni Galaxy S24 Ultra, forma supreme e Galaxy Ultra me Galaxy AI. Është dizajn ikonik me kornizë të re titanium.",
    price_all: 149900,
    price_eur: 1299,
    original_price_all: 169900,
    original_price_eur: 1449,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.6,
    rating_count: 178,
    category: "phones",
    brand: "Samsung",
  },
  {
    id: "6",
    slug: "ipad-pro-12-9-m2",
    name_en: "iPad Pro 12.9\" M2 WiFi 256GB",
    name_sq: "iPad Pro 12.9\" M2 WiFi 256GB",
    short_description_en: "M2 chip, Liquid Retina XDR display, Apple Pencil",
    short_description_sq: "M2 çip, Ekran Liquid Retina XDR, Apple Pencil",
    description_en: "Supercharged by the M2 chip. iPad Pro has an immersive Liquid Retina XDR display.",
    description_sq: "I mbingarkuar nga çipi M2. iPad Pro ka ekran përfshirës Liquid Retina XDR.",
    price_all: 139900,
    price_eur: 1199,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.8,
    rating_count: 156,
    category: "phones",
    brand: "Apple",
  },
  // TV & AUDIO
  {
    id: "7",
    slug: "sony-bravia-65-oled",
    name_en: "Sony Bravia XR 65\" 4K OLED",
    name_sq: "Sony Bravia XR 65\" 4K OLED",
    short_description_en: "4K HDR, 120Hz, Google TV, Dolby Atmos",
    short_description_sq: "4K HDR, 120Hz, Google TV, Dolby Atmos",
    description_en: "Experience lifelike picture with cognitive processor XR. Perfect for movies, sports and gaming.",
    description_sq: "Përjetoni pamje realiste me procesorin kognitiv XR. Perfekt për filma, sport dhe lojëra.",
    price_all: 229900,
    price_eur: 1999,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 89,
    category: "tv",
    brand: "Sony",
  },
  {
    id: "8",
    slug: "lg-oled-c3-55",
    name_en: "LG OLED C3 55\" 4K Smart TV",
    name_sq: "LG OLED C3 55\" 4K Smart TV",
    short_description_en: "OLED evo, α9 AI Processor, 120Hz Gaming",
    short_description_sq: "OLED evo, α9 AI Procesor, 120Hz Gaming",
    description_en: "Self-lit pixels and deep black enhance picture quality. Perfect OLED with brilliant colors.",
    description_sq: "Pikselët vetë-ndriçues dhe e zeza e thellë përmirësojnë cilësinë e pamjes. OLED perfekt me ngjyra të shkëlqyera.",
    price_all: 149900,
    price_eur: 1299,
    original_price_all: 179900,
    original_price_eur: 1549,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.8,
    rating_count: 234,
    category: "tv",
    brand: "LG",
  },
  {
    id: "9",
    slug: "sony-wh-1000xm5",
    name_en: "Sony WH-1000XM5 Headphones",
    name_sq: "Sony WH-1000XM5 Kufje",
    short_description_en: "Industry-leading noise cancellation, 30hr battery",
    short_description_sq: "Anulim zhurme lider në industri, 30 orë bateri",
    description_en: "Industry-leading noise cancellation and exceptional sound quality in an iconic, comfortable design.",
    description_sq: "Anulim zhurme lider në industri dhe cilësi e jashtëzakonshme zëri në dizajn ikonik dhe të rehatshëm.",
    price_all: 39900,
    price_eur: 349,
    original_price_all: 44900,
    original_price_eur: 399,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.9,
    rating_count: 567,
    category: "tv",
    brand: "Sony",
  },
  {
    id: "10",
    slug: "apple-airpods-pro-2",
    name_en: "Apple AirPods Pro (2nd Gen)",
    name_sq: "Apple AirPods Pro (Gjenerata 2)",
    short_description_en: "Active Noise Cancellation, H2 chip, MagSafe",
    short_description_sq: "Anulim Aktiv i Zhurmës, çip H2, MagSafe",
    description_en: "Rebuilt from the sound up. AirPods Pro now feature a next-level noise cancellation and immersive Spatial Audio.",
    description_sq: "I rindërtuar nga zëri lart. AirPods Pro tani kanë anulim zhurme të nivelit tjetër dhe Audio Hapësinore përfshirëse.",
    price_all: 29900,
    price_eur: 259,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 892,
    category: "tv",
    brand: "Apple",
  },
  // GAMING
  {
    id: "11",
    slug: "ps5-console-bundle",
    name_en: "PlayStation 5 Console Bundle",
    name_sq: "PlayStation 5 Paketë Konsole",
    short_description_en: "825GB SSD, 4K Gaming, DualSense, Extra Controller",
    short_description_sq: "825GB SSD, 4K Gaming, DualSense, Kontrollues Ekstra",
    description_en: "Experience lightning-fast loading with an ultra-high speed SSD, haptic feedback, and adaptive triggers.",
    description_sq: "Përjetoni ngarkim si rrufeja me SSD ultra të shpejtë, reagim haptik dhe këmbëza adaptive.",
    price_all: 69900,
    price_eur: 599,
    original_price_all: 79900,
    original_price_eur: 699,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.9,
    rating_count: 412,
    category: "gaming",
    brand: "Sony",
  },
  {
    id: "12",
    slug: "xbox-series-x",
    name_en: "Xbox Series X 1TB",
    name_sq: "Xbox Series X 1TB",
    short_description_en: "1TB SSD, 4K at 120fps, Xbox Game Pass",
    short_description_sq: "1TB SSD, 4K në 120fps, Xbox Game Pass",
    description_en: "The fastest, most powerful Xbox ever. Play thousands of titles from four generations of consoles.",
    description_sq: "Xbox më i shpejtë dhe më i fuqishëm ndonjëherë. Luani mijëra tituj nga katër gjenerata konsolash.",
    price_all: 59900,
    price_eur: 499,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.8,
    rating_count: 287,
    category: "gaming",
    brand: "Microsoft",
  },
  {
    id: "13",
    slug: "nintendo-switch-oled",
    name_en: "Nintendo Switch OLED Model",
    name_sq: "Nintendo Switch Modeli OLED",
    short_description_en: "7\" OLED Screen, 64GB Storage, Dock included",
    short_description_sq: "7\" Ekran OLED, 64GB Hapësirë, Dok i përfshirë",
    description_en: "Featuring a vibrant 7-inch OLED screen and a wide adjustable stand for tabletop mode.",
    description_sq: "Me ekran OLED 7 inç të gjallë dhe mbështetëse të rregullueshme të gjerë për modalitetin e tavolinës.",
    price_all: 39900,
    price_eur: 349,
    original_price_all: 44900,
    original_price_eur: 389,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 356,
    category: "gaming",
    brand: "Nintendo",
  },
  // SMART HOME & ACCESSORIES
  {
    id: "14",
    slug: "apple-watch-series-9",
    name_en: "Apple Watch Series 9 GPS 45mm",
    name_sq: "Apple Watch Series 9 GPS 45mm",
    short_description_en: "S9 chip, Always-On Retina, Double Tap gesture",
    short_description_sq: "S9 çip, Always-On Retina, gjestet Double Tap",
    description_en: "A magical new way to use your Apple Watch without touching the display. Double Tap lets you easily control your watch.",
    description_sq: "Një mënyrë e re magjike për të përdorur Apple Watch pa prekur ekranin. Double Tap ju lejon të kontrolloni lehtësisht orën tuaj.",
    price_all: 49900,
    price_eur: 429,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.8,
    rating_count: 234,
    category: "accessories",
    brand: "Apple",
  },
  {
    id: "15",
    slug: "samsung-galaxy-watch-6",
    name_en: "Samsung Galaxy Watch 6 Classic",
    name_sq: "Samsung Galaxy Watch 6 Classic",
    short_description_en: "Rotating bezel, Sleep tracking, Body Composition",
    short_description_sq: "Bezel rrotullues, Gjurmim gjumi, Përbërje trupi",
    description_en: "Classic rotating bezel is back. Premium design meets advanced health monitoring.",
    description_sq: "Bezeli klasik rrotullues është kthyer. Dizajni premium takon monitorimin e avancuar shëndetësor.",
    price_all: 39900,
    price_eur: 349,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.5,
    rating_count: 189,
    category: "accessories",
    brand: "Samsung",
  },
  {
    id: "16",
    slug: "dyson-v15-detect",
    name_en: "Dyson V15 Detect Absolute",
    name_sq: "Dyson V15 Detect Absolute",
    short_description_en: "Laser dust detection, LCD screen, 60min runtime",
    short_description_sq: "Detekim pluhuri me lazer, ekran LCD, 60min kohë pune",
    description_en: "Reveals hidden dust with a precisely-angled laser. Shows what's been sucked up on the LCD screen.",
    description_sq: "Zbulon pluhurin e fshehur me lazer të përpiktë të këndit. Tregon çfarë është thithur në ekranin LCD.",
    price_all: 79900,
    price_eur: 699,
    original_price_all: 89900,
    original_price_eur: 779,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.6,
    rating_count: 145,
    category: "accessories",
    brand: "Dyson",
  },
  // MORE COMPUTERS
  {
    id: "17",
    slug: "macbook-air-15-m3",
    name_en: "MacBook Air 15\" M3",
    name_sq: "MacBook Air 15\" M3",
    short_description_en: "Apple M3 chip, 16GB RAM, 512GB SSD, Midnight",
    short_description_sq: "Apple M3 çip, 16GB RAM, 512GB SSD, Midnight",
    description_en: "Impressively thin design, all-day battery life, and the power of M3 make MacBook Air perfect for work and play.",
    description_sq: "Dizajn mbresëlënës i hollë, bateri gjatë gjithë ditës, dhe fuqia e M3 e bëjnë MacBook Air perfekt për punë dhe lojë.",
    price_all: 189900,
    price_eur: 1649,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 98,
    category: "computers",
    brand: "Apple",
  },
  {
    id: "18",
    slug: "hp-spectre-x360",
    name_en: "HP Spectre x360 14\" 2-in-1",
    name_sq: "HP Spectre x360 14\" 2-në-1",
    short_description_en: "Intel Core Ultra 7, 32GB RAM, 3K OLED Touch",
    short_description_sq: "Intel Core Ultra 7, 32GB RAM, 3K OLED Touch",
    description_en: "Premium 2-in-1 laptop with stunning OLED display, all-day battery, and versatile design.",
    description_sq: "Laptop premium 2-në-1 me ekran OLED mahnitës, bateri gjatë gjithë ditës, dhe dizajn të shumanshëm.",
    price_all: 199900,
    price_eur: 1749,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.4,
    rating_count: 76,
    category: "computers",
    brand: "Dell",
  },
  // MORE PHONES
  {
    id: "19",
    slug: "google-pixel-8-pro",
    name_en: "Google Pixel 8 Pro 256GB",
    name_sq: "Google Pixel 8 Pro 256GB",
    short_description_en: "6.7\" LTPO OLED, Tensor G3, 50MP Camera",
    short_description_sq: "6.7\" LTPO OLED, Tensor G3, 50MP Kamera",
    description_en: "Google's most advanced phone with the best of Google AI, incredible camera, and 7 years of updates.",
    description_sq: "Telefoni më i avancuar i Google me AI-n më të mirë të Google, kamera e jashtëzakonshme, dhe 7 vite përditësime.",
    price_all: 119900,
    price_eur: 1049,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.6,
    rating_count: 145,
    category: "phones",
    brand: "Samsung",
  },
  {
    id: "20",
    slug: "iphone-15-128gb",
    name_en: "iPhone 15 128GB",
    name_sq: "iPhone 15 128GB",
    short_description_en: "6.1\" Super Retina XDR, A16 Bionic, USB-C",
    short_description_sq: "6.1\" Super Retina XDR, A16 Bionic, USB-C",
    description_en: "Dynamic Island. 48MP camera. A16 Bionic chip. And USB-C. All in a durable design with new colors.",
    description_sq: "Dynamic Island. Kamera 48MP. Çip A16 Bionic. Dhe USB-C. Të gjitha në dizajn të qëndrueshëm me ngjyra të reja.",
    price_all: 99900,
    price_eur: 869,
    original_price_all: 109900,
    original_price_eur: 949,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 324,
    category: "phones",
    brand: "Apple",
  },
  {
    id: "21",
    slug: "samsung-galaxy-a54",
    name_en: "Samsung Galaxy A54 5G",
    name_sq: "Samsung Galaxy A54 5G",
    short_description_en: "6.4\" Super AMOLED, 50MP Camera, Water Resistant",
    short_description_sq: "6.4\" Super AMOLED, 50MP Kamera, Rezistent ndaj Ujit",
    description_en: "Awesome display, awesome camera, awesome performance - all in one phone at a great price.",
    description_sq: "Ekran i mrekullueshëm, kamera e mrekullueshme, performancë e mrekullueshme - të gjitha në një telefon me çmim të shkëlqyer.",
    price_all: 44900,
    price_eur: 389,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.3,
    rating_count: 567,
    category: "phones",
    brand: "Samsung",
  },
  // MORE TV & AUDIO
  {
    id: "22",
    slug: "samsung-qn85b-55",
    name_en: "Samsung QN85B 55\" Neo QLED 4K",
    name_sq: "Samsung QN85B 55\" Neo QLED 4K",
    short_description_en: "Neo Quantum Processor 4K, Object Tracking Sound",
    short_description_sq: "Neo Quantum Processor 4K, Object Tracking Sound",
    description_en: "Mini LED backlighting delivers deeper blacks and more vibrant colors than ever before.",
    description_sq: "Ndriçimi Mini LED ofron të zeza më të thella dhe ngjyra më të gjalla se kurrë më parë.",
    price_all: 129900,
    price_eur: 1129,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.5,
    rating_count: 178,
    category: "tv",
    brand: "Samsung",
  },
  {
    id: "23",
    slug: "sonos-arc-soundbar",
    name_en: "Sonos Arc Premium Soundbar",
    name_sq: "Sonos Arc Soundbar Premium",
    short_description_en: "Dolby Atmos, 11 Drivers, Voice Control",
    short_description_sq: "Dolby Atmos, 11 Drejtues, Kontroll me Zë",
    description_en: "Premium smart soundbar for TV, movies, music, gaming, and more. Immersive Dolby Atmos sound.",
    description_sq: "Soundbar smart premium për TV, filma, muzikë, lojëra, dhe më shumë. Zë përfshirës Dolby Atmos.",
    price_all: 99900,
    price_eur: 869,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.8,
    rating_count: 234,
    category: "tv",
    brand: "Sony",
  },
  {
    id: "24",
    slug: "jbl-charge-5",
    name_en: "JBL Charge 5 Portable Speaker",
    name_sq: "JBL Charge 5 Altoparlant Portativ",
    short_description_en: "Waterproof, 20hr Battery, Powerbank function",
    short_description_sq: "Rezistent ndaj ujit, 20 orë Bateri, Funksion Powerbank",
    description_en: "Take your music on the go with JBL Charge 5. IP67 waterproof and up to 20 hours of playtime.",
    description_sq: "Merrni muzikën tuaj kudo me JBL Charge 5. IP67 rezistent ndaj ujit dhe deri në 20 orë luajtje.",
    price_all: 19900,
    price_eur: 169,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.6,
    rating_count: 892,
    category: "tv",
    brand: "Sony",
  },
  // MORE GAMING
  {
    id: "25",
    slug: "ps5-dualsense-edge",
    name_en: "PS5 DualSense Edge Controller",
    name_sq: "PS5 DualSense Edge Kontrollues",
    short_description_en: "Customizable controls, Replaceable sticks, Pro gaming",
    short_description_sq: "Kontrolle të personalizueshme, Shkopinj të zëvendësueshëm",
    description_en: "The ultra-customizable controller for competitive gamers. Designed for peak performance.",
    description_sq: "Kontrolluesi ultra i personalizueshëm për lojtarë konkurues. Projektuar për performancë maksimale.",
    price_all: 24900,
    price_eur: 219,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 156,
    category: "gaming",
    brand: "Sony",
  },
  {
    id: "26",
    slug: "razer-blackwidow-v4",
    name_en: "Razer BlackWidow V4 Pro Keyboard",
    name_sq: "Razer BlackWidow V4 Pro Tastierë",
    short_description_en: "Mechanical switches, RGB Chroma, Wrist rest",
    short_description_sq: "Çelësa mekanikë, RGB Chroma, Mbështetëse dore",
    description_en: "The esports keyboard featuring Razer Green Mechanical Switches and customizable RGB lighting.",
    description_sq: "Tastiera e esports me Çelësa Mekanikë Razer Green dhe ndriçim RGB të personalizueshëm.",
    price_all: 22900,
    price_eur: 199,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.5,
    rating_count: 234,
    category: "gaming",
    brand: "ASUS",
  },
  {
    id: "27",
    slug: "logitech-g-pro-x",
    name_en: "Logitech G PRO X Gaming Headset",
    name_sq: "Logitech G PRO X Kufje Gaming",
    short_description_en: "PRO-G 50mm Drivers, Blue VO!CE Mic, 7.1 Surround",
    short_description_sq: "PRO-G 50mm Drejtues, Blue VO!CE Mic, 7.1 Surround",
    description_en: "Built with and for esports pros. Blue VO!CE technology for real-time voice enhancement.",
    description_sq: "Ndërtuar me dhe për profesionistë esports. Teknologji Blue VO!CE për përmirësim të zërit në kohë reale.",
    price_all: 14900,
    price_eur: 129,
    original_price_all: 17900,
    original_price_eur: 155,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1599669454699-248893623440?w=800", is_primary: true },
    ],
    is_on_sale: true,
    is_in_stock: true,
    rating_average: 4.6,
    rating_count: 445,
    category: "gaming",
    brand: "Microsoft",
  },
  // MORE ACCESSORIES
  {
    id: "28",
    slug: "anker-powercore-26800",
    name_en: "Anker PowerCore 26800mAh",
    name_sq: "Anker PowerCore 26800mAh",
    short_description_en: "High capacity, 3 USB ports, Fast charging",
    short_description_sq: "Kapacitet i lartë, 3 porta USB, Ngarkim i shpejtë",
    description_en: "One of the highest capacity portable chargers. Charges an iPhone 8 over 10 times.",
    description_sq: "Një nga ngarkuesit portativë me kapacitet më të lartë. Ngarkon një iPhone 8 mbi 10 herë.",
    price_all: 6900,
    price_eur: 59,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.7,
    rating_count: 1234,
    category: "accessories",
    brand: "Samsung",
  },
  {
    id: "29",
    slug: "belkin-magsafe-charger",
    name_en: "Belkin 3-in-1 MagSafe Charger",
    name_sq: "Belkin 3-në-1 Ngarkues MagSafe",
    short_description_en: "iPhone, Apple Watch, AirPods charging stand",
    short_description_sq: "Bazë ngarkimi për iPhone, Apple Watch, AirPods",
    description_en: "Official MagSafe charger for all your Apple devices. Fast wireless charging in a sleek design.",
    description_sq: "Ngarkues zyrtar MagSafe për të gjitha pajisjet tuaja Apple. Ngarkim i shpejtë pa tel në dizajn elegant.",
    price_all: 17900,
    price_eur: 155,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1622782914767-404fb9ab3f57?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.5,
    rating_count: 289,
    category: "accessories",
    brand: "Apple",
  },
  {
    id: "30",
    slug: "logitech-mx-master-3s",
    name_en: "Logitech MX Master 3S Mouse",
    name_sq: "Logitech MX Master 3S Mouse",
    short_description_en: "Quiet clicks, 8K DPI, Multi-device, USB-C",
    short_description_sq: "Klikime të qeta, 8K DPI, Multi-pajisje, USB-C",
    description_en: "The most advanced Master Series mouse yet. Quiet clicks, 8K DPI tracking, and works on any surface.",
    description_sq: "Mouse-i Master Series më i avancuar deri tani. Klikime të qeta, gjurmim 8K DPI, dhe punon në çdo sipërfaqe.",
    price_all: 12900,
    price_eur: 109,
    product_images: [
      { image_url: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800", is_primary: true },
    ],
    is_on_sale: false,
    is_in_stock: true,
    rating_average: 4.8,
    rating_count: 678,
    category: "accessories",
    brand: "Microsoft",
  },
]

export const categories = [
  { id: "computers", name_en: "Computers & Laptops", name_sq: "Kompjuterë & Laptopë" },
  { id: "phones", name_en: "Phones & Tablets", name_sq: "Telefona & Tableta" },
  { id: "tv", name_en: "TV & Audio", name_sq: "TV & Audio" },
  { id: "gaming", name_en: "Gaming", name_sq: "Gaming" },
  { id: "accessories", name_en: "Accessories", name_sq: "Aksesorë" },
]

export const brands = ["Apple", "Samsung", "Sony", "Dell", "LG", "ASUS", "Microsoft", "Nintendo", "Dyson", "Logitech", "Razer", "JBL", "Sonos", "Anker", "Belkin", "Google", "HP"]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(p => p.category === categoryId)
}

export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return products
    .filter(p => p.category === product.category && p.id !== product.id)
    .slice(0, limit)
}

export function getProductsOnSale(limit?: number): Product[] {
  const saleProducts = products.filter(p => p.is_on_sale && p.original_price_all)
  return limit ? saleProducts.slice(0, limit) : saleProducts
}
